---
- name: Install HAProxy
  apt:
    name: haproxy
    state: present

- name: Copy Configuration Files
  template:
    src: templates/haproxy.cfg.j2
    dest: "/etc/haproxy/haproxy.cfg"
  notify: Restart HAProxy service
