---
- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: false

- name: Install Docker Compose
  apt:
    name: docker-compose
    state: present
    update_cache: false

- name: Ensure Docker service is running
  systemd:
    name: docker
    state: started
    enabled: false