---
- hosts: loadbalancer_master
  become: true
  vars_files:
    - vars/globalvars.yml
    - vars/vault.yml
  pre_tasks:
    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: false  
      loop:
        - acl
        - postgresql-client
        - python3-psycopg2
        - python3-passlib

  roles:
    - postgres
    - pdnsadmin
    - powerdns
    - keepalived
    - haproxy
    - gitea
    - registry