---
- name: Install Docker
  import_tasks: ../../tasks/docker.yml

- name: Create Postgresql Userdb
  import_tasks: ../../tasks/postgres-userdb.yml
  vars:
    postgres_db: "{{ pdnsa_postgres_db }}"
    postgres_user: "{{ pdnsa_postgres_user }}"
    postgres_userpass: "{{ pdnsa_postgres_userpass }}"
    postgres_host: "{{ pdnsa_postgres_host }}"
    postgres_port: "{{ pdnsa_postgres_port }}"

- name: Install System Service for Application
  import_tasks: ../../tasks/docker-service.yml

